services:
  - type: worker
    name: text-uploader-bot
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    startCommand: sh start.sh
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false